runtime: python27
api_version: 1
threadsafe: true

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 1m

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /Start/.*
  script: main.app
  login: admin

- url: /Stop/.*
  script: main.app
  login: admin

- url: /Monitor
  script: main.app
  login: admin

- url: /StopAll
  script: main.app

- url: /Status
  script: main.app

- url: /
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
